[phases.setup]
nixPkgs = [
  "python311Full",
  "python311Packages.flask",
  "python311Packages.flask_sqlalchemy",
  "python311Packages.flask_migrate",
  "python311Packages.gunicorn",
  "python311Packages.python-dotenv",
  "python311Packages.sqlalchemy",
  "python311Packages.jinja2",
  "python311Packages.markupsafe",
  "python311Packages.itsdangerous",
  "python311Packages.werkzeug",
  "python311Packages.click",
  "python311Packages.blinker",
  "python311Packages.greenlet",
  "python311Packages.packaging",
  "python311Packages.typing-extensions",
  "python311Packages.colorama",
  "python311Packages.mako",
  "python311Packages.alembic"
]

[start]
cmd = "python site.py"
