[phases.setup]
nixPkgs = [
  "python311Full",
  "git",
  "python311Packages.pip",
  "python311Packages.gunicorn"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn site:app --bind 0.0.0.0:$PORT"
