[phases.setup]
nixPkgs = ["python311", "pip", "git"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn site:app --bind 0.0.0.0:$PORT"